Added typings
mia-platform/flow-manager-client pull request #31
Opened 2021-12-08 09:56 UTC by epessina

Added TypeScript typings.

#### Checklist

- [x] your branch will not cause merge conflict with `master`
- [x] run `npm test`
- [x] tests are included
- [x] the documentation is updated or integrated accordingly with your changes
- [x] the code will follow the lint rules and style of the project
- [x] you are not committing extraneous files or sensible data

2021-12-12 10:16 UTC, epessina commented
Ping

2021-12-27 08:35 UTC, davidebianchi requested changes
Why package-lock.json is +6k lines smaller than main?

2021-12-27 08:35 UTC, davidebianchi commented on package.json
> +    "typescript": "tsc --project ./tests/types/tsconfig.json",
We should add the types field [as in this link](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)

2021-12-27 08:35 UTC, davidebianchi commented on tests/types/index.ts
> +console.log(ClientBuilder.log)
Instead of test with console.log, we should use something like https://github.com/SamVerschueren/tsd to test the expected types

2021-12-27 19:57 UTC, epessina commented
> Why package-lock.json is +6k lines smaller than main?

I was using an old version of npm. I've upgraded it and fixed the lockfile.

2022-01-13 16:43 UTC, epessina commented
Ping!

2022-01-14 08:12 UTC, merged